// Class: ReadMLPDYQ3Type6
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================
#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-
Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/05       [393733]
Creator        : aackert
Date           : Wed Feb  1 07:00:08 2017
Host           : Linux cmsbuild12.cern.ch 2.6.32-573.7.1.el6.x86_64 #1 SMP Wed Sep 23 10:12:03 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/aackert/private/CMSSW_7_4_15/src/MVA/exercises/03_TMVA
Training events: 20000
Analysis type  : [Classification]
#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-
# Set by User:
HiddenLayers: "10TrainingMethod=BFGS" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
# Default:
NCycles: "500" [Number of training cycles]
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##
#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-
NVar 3
P                             P                             P                             P                                                               'F'    [60.0715484619,3596.5949707]
Ih                            Ih                            Ih                            Ih                                                              'F'    [1.53014445305,27.7582359314]
eta                           eta                           eta                           eta                                                             'F'    [-2.09828233719,2.09991383553]
NSpec 0
============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

public:

  // constructor
  IClassifierReader() : fStatusIsClean( true ) {}
  virtual ~IClassifierReader() {}

  // return classifier response
  virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

  // returns classifier status
  bool IsStatusClean() const { return fStatusIsClean; }

protected:

  bool fStatusIsClean;
};

#endif

class ReadMLPDYQ3Type6 : public IClassifierReader {

public:

  // constructor
  ReadMLPDYQ3Type6( std::vector<std::string>& theInputVars ) 
    : IClassifierReader(),
      fClassName( "ReadMLPDYQ3Type6" ),
      fNvars( 3 ),
      fIsNormalised( false )
  {      
    // the training input variables
    const char* inputVars[] = { "P", "Ih", "eta" };

    // sanity checks
    if (theInputVars.size() <= 0) {
      std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
      fStatusIsClean = false;
    }

    if (theInputVars.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
		<< theInputVars.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
    }

    // validate input variables
    for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
      if (theInputVars[ivar] != inputVars[ivar]) {
	std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
		  << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
	fStatusIsClean = false;
      }
    }

    // initialize min and max vectors (for normalisation)
    fVmin[0] = -1;
    fVmax[0] = 0.99999988079071;
    fVmin[1] = -1;
    fVmax[1] = 1;
    fVmin[2] = -1;
    fVmax[2] = 1;

    // initialize input variable types
    fType[0] = 'F';
    fType[1] = 'F';
    fType[2] = 'F';

    // initialize constants
    Initialize();

    // initialize transformation
    InitTransform();
  }

  // destructor
  virtual ~ReadMLPDYQ3Type6() {
    Clear(); // method-specific
  }

  // the classifier response
  // "inputValues" is a vector of input values in the same order as the 
  // variables given to the constructor
  double GetMvaValue( const std::vector<double>& inputValues ) const;

private:

  // method-specific destructor
  void Clear();

  // input variable transformation

  double fMin_1[3][3];
  double fMax_1[3][3];
  void InitTransform_1();
  void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
  void InitTransform();
  void Transform( std::vector<double> & iv, int sigOrBgd ) const;

  // common member variables
  const char* fClassName;

  const size_t fNvars;
  size_t GetNvar()           const { return fNvars; }
  char   GetType( int ivar ) const { return fType[ivar]; }

  // normalisation of input variables
  const bool fIsNormalised;
  bool IsNormalised() const { return fIsNormalised; }
  double fVmin[3];
  double fVmax[3];
  double NormVariable( double x, double xmin, double xmax ) const {
    // normalise to output range: [-1, 1]
    return 2*(x - xmin)/(xmax - xmin) - 1.0;
  }

  // type of input variable: 'F' or 'I'
  char   fType[3];

  // initialize internal variables
  void Initialize();
  double GetMvaValue__( const std::vector<double>& inputValues ) const;

  // private members (method specific)

  double ActivationFnc(double x) const;
  double OutputActivationFnc(double x) const;

  int fLayers;
  int fLayerSize[3];
  double fWeightMatrix0to1[11][4];   // weight matrix from layer 0 to 1
  double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

  double * fWeights[3];
};

inline void ReadMLPDYQ3Type6::Initialize()
{
  // build network structure
  fLayers = 3;
  fLayerSize[0] = 4; fWeights[0] = new double[4]; 
  fLayerSize[1] = 11; fWeights[1] = new double[11]; 
  fLayerSize[2] = 1; fWeights[2] = new double[1]; 
  // weight matrix from layer 0 to 1
  fWeightMatrix0to1[0][0] = 0.0328396398175084;
  fWeightMatrix0to1[1][0] = 8.35451263056992;
  fWeightMatrix0to1[2][0] = 0.830490450482663;
  fWeightMatrix0to1[3][0] = 1.20784963520698;
  fWeightMatrix0to1[4][0] = -0.176550424449504;
  fWeightMatrix0to1[5][0] = -1.29707004592575;
  fWeightMatrix0to1[6][0] = -0.976066570647838;
  fWeightMatrix0to1[7][0] = 1.62619365414054;
  fWeightMatrix0to1[8][0] = -0.686696069604186;
  fWeightMatrix0to1[9][0] = -3.86094314431088;
  fWeightMatrix0to1[0][1] = -1.51058377066048;
  fWeightMatrix0to1[1][1] = -1.73235256725821;
  fWeightMatrix0to1[2][1] = -0.248174444490407;
  fWeightMatrix0to1[3][1] = 0.127711490687107;
  fWeightMatrix0to1[4][1] = -1.1373958983665;
  fWeightMatrix0to1[5][1] = 0.439156604523182;
  fWeightMatrix0to1[6][1] = 0.134508456020961;
  fWeightMatrix0to1[7][1] = 1.8400514351399;
  fWeightMatrix0to1[8][1] = 0.98684304768486;
  fWeightMatrix0to1[9][1] = 4.18288406041942;
  fWeightMatrix0to1[0][2] = -0.249626732346038;
  fWeightMatrix0to1[1][2] = -0.0710488343392106;
  fWeightMatrix0to1[2][2] = 0.147987717849764;
  fWeightMatrix0to1[3][2] = -0.0976887142215546;
  fWeightMatrix0to1[4][2] = 0.0901638043982665;
  fWeightMatrix0to1[5][2] = -0.77209575695086;
  fWeightMatrix0to1[6][2] = 1.54129102510075;
  fWeightMatrix0to1[7][2] = -0.0709506409861983;
  fWeightMatrix0to1[8][2] = -1.41848884821402;
  fWeightMatrix0to1[9][2] = 0.0603086208333082;
  fWeightMatrix0to1[0][3] = 0.65634752738662;
  fWeightMatrix0to1[1][3] = 5.35428099735864;
  fWeightMatrix0to1[2][3] = -0.67081088704389;
  fWeightMatrix0to1[3][3] = -0.0342941055570067;
  fWeightMatrix0to1[4][3] = 0.423367579233141;
  fWeightMatrix0to1[5][3] = -3.39663951827515;
  fWeightMatrix0to1[6][3] = -3.17365927072536;
  fWeightMatrix0to1[7][3] = 2.62081590905055;
  fWeightMatrix0to1[8][3] = -1.58355489294007;
  fWeightMatrix0to1[9][3] = -0.358576397995189;
  // weight matrix from layer 1 to 2
  fWeightMatrix1to2[0][0] = -0.440987340666501;
  fWeightMatrix1to2[0][1] = 2.71751835425705;
  fWeightMatrix1to2[0][2] = 0.509155322835633;
  fWeightMatrix1to2[0][3] = 0.0151640511849603;
  fWeightMatrix1to2[0][4] = -1.12975888845196;
  fWeightMatrix1to2[0][5] = -2.16692347789738;
  fWeightMatrix1to2[0][6] = -1.47182216292191;
  fWeightMatrix1to2[0][7] = -0.314933764659088;
  fWeightMatrix1to2[0][8] = -0.271434422634446;
  fWeightMatrix1to2[0][9] = 2.74670008341386;
  fWeightMatrix1to2[0][10] = -0.35016271823308;
}

inline double ReadMLPDYQ3Type6::GetMvaValue__( const std::vector<double>& inputValues ) const
{
  if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
    std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
    return 0;
  }

  for (int l=0; l<fLayers; l++)
    for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

  for (int l=0; l<fLayers-1; l++)
    fWeights[l][fLayerSize[l]-1]=1;

  for (int i=0; i<fLayerSize[0]-1; i++)
    fWeights[0][i]=inputValues[i];

  // layer 0 to 1
  for (int o=0; o<fLayerSize[1]-1; o++) {
    for (int i=0; i<fLayerSize[0]; i++) {
      double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
      fWeights[1][o] += inputVal;
    }
    fWeights[1][o] = ActivationFnc(fWeights[1][o]);
  }
  // layer 1 to 2
  for (int o=0; o<fLayerSize[2]; o++) {
    for (int i=0; i<fLayerSize[1]; i++) {
      double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
      fWeights[2][o] += inputVal;
    }
    fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
  }

  return fWeights[2][0];
}

double ReadMLPDYQ3Type6::ActivationFnc(double x) const {
  // sigmoid
  return 1.0/(1.0+exp(-x));
}
double ReadMLPDYQ3Type6::OutputActivationFnc(double x) const {
  // identity
  return x;
}
   
// Clean up
inline void ReadMLPDYQ3Type6::Clear() 
{
  // clean up the arrays
  for (int lIdx = 0; lIdx < 3; lIdx++) {
    delete[] fWeights[lIdx];
  }
}
inline double ReadMLPDYQ3Type6::GetMvaValue( const std::vector<double>& inputValues ) const
{
  // classifier response value
  double retval = 0;

  // classifier response, sanity check first
  if (!IsStatusClean()) {
    std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
	      << " because status is dirty" << std::endl;
    retval = 0;
  }
  else {
    if (IsNormalised()) {
      // normalise variables
      std::vector<double> iV;
      iV.reserve(inputValues.size());
      int ivar = 0;
      for (std::vector<double>::const_iterator varIt = inputValues.begin();
	   varIt != inputValues.end(); varIt++, ivar++) {
	iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
      }
      Transform( iV, -1 );
      retval = GetMvaValue__( iV );
    }
    else {
      std::vector<double> iV;
      int ivar = 0;
      for (std::vector<double>::const_iterator varIt = inputValues.begin();
	   varIt != inputValues.end(); varIt++, ivar++) {
	iV.push_back(*varIt);
      }
      Transform( iV, -1 );
      retval = GetMvaValue__( iV );
    }
  }

  return retval;
}

//_______________________________________________________________________
inline void ReadMLPDYQ3Type6::InitTransform_1()
{
  // Normalization transformation, initialisation
  fMin_1[0][0] = 86.1430664062;
  fMax_1[0][0] = 3596.5949707;
  fMin_1[1][0] = 60.0715484619;
  fMax_1[1][0] = 1240.82495117;
  fMin_1[2][0] = 60.0715484619;
  fMax_1[2][0] = 3596.5949707;
  fMin_1[0][1] = 1.53014445305;
  fMax_1[0][1] = 27.7582359314;
  fMin_1[1][1] = 2.26485323906;
  fMax_1[1][1] = 6.35099983215;
  fMin_1[2][1] = 1.53014445305;
  fMax_1[2][1] = 27.7582359314;
  fMin_1[0][2] = -2.09801650047;
  fMax_1[0][2] = 2.09991383553;
  fMin_1[1][2] = -2.09828233719;
  fMax_1[1][2] = 2.09932804108;
  fMin_1[2][2] = -2.09828233719;
  fMax_1[2][2] = 2.09991383553;
}

//_______________________________________________________________________
inline void ReadMLPDYQ3Type6::Transform_1( std::vector<double>& iv, int cls) const
{
  // Normalization transformation
  if (cls < 0 || cls > 2) {
    if (2 > 1 ) cls = 2;
    else cls = 2;
  }
  const int nVar = 3;

  // get indices of used variables

  // define the indices of the variables which are transformed by this transformation
  static std::vector<int> indicesGet;
  static std::vector<int> indicesPut;

  if ( indicesGet.empty() ) { 
    indicesGet.reserve(fNvars);
    indicesGet.push_back( 0);
    indicesGet.push_back( 1);
    indicesGet.push_back( 2);
  } 
  if ( indicesPut.empty() ) { 
    indicesPut.reserve(fNvars);
    indicesPut.push_back( 0);
    indicesPut.push_back( 1);
    indicesPut.push_back( 2);
  } 

  static std::vector<double> dv;
  dv.resize(nVar);
  for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
  for (int ivar=0;ivar<3;ivar++) {
    double offset = fMin_1[cls][ivar];
    double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
    iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
  }
}

//_______________________________________________________________________
inline void ReadMLPDYQ3Type6::InitTransform()
{
  InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPDYQ3Type6::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
  Transform_1( iv, sigOrBgd );
}
