// Class: ReadMLPGluinoType7
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================
#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-
Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/05       [393733]
Creator        : aackert
Date           : Tue Feb 14 05:22:15 2017
Host           : Linux cmsbuild12.cern.ch 2.6.32-573.7.1.el6.x86_64 #1 SMP Wed Sep 23 10:12:03 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/aackert/private/CMSSW_7_4_15/src/MVA/exercises/03_TMVA
Training events: 20000
Analysis type  : [Classification]
#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-
# Set by User:
HiddenLayers: "10" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
# Default:
NCycles: "500" [Number of training cycles]
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##
#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-
NVar 4
P                             P                             P                             P                                                               'F'    [60.0310516357,3768.42919922]
Ih                            Ih                            Ih                            Ih                                                              'F'    [0.830619454384,492.651397705]
eta                           eta                           eta                           eta                                                             'F'    [-2.09951782227,2.09895896912]
TOF                           TOF                           TOF                           TOF                                                             'F'    [1.02580487728,4607.02197266]
NSpec 0
============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

public:

  // constructor
  IClassifierReader() : fStatusIsClean( true ) {}
  virtual ~IClassifierReader() {}

  // return classifier response
  virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

  // returns classifier status
  bool IsStatusClean() const { return fStatusIsClean; }

protected:

  bool fStatusIsClean;
};

#endif

class ReadMLPGluinoType7 : public IClassifierReader {

public:

  // constructor
  ReadMLPGluinoType7( std::vector<std::string>& theInputVars ) 
    : IClassifierReader(),
      fClassName( "ReadMLPGluinoType7" ),
      fNvars( 4 ),
      fIsNormalised( false )
  {      
    // the training input variables
    const char* inputVars[] = { "P", "Ih", "eta", "TOF" };

    // sanity checks
    if (theInputVars.size() <= 0) {
      std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
      fStatusIsClean = false;
    }

    if (theInputVars.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
		<< theInputVars.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
    }

    // validate input variables
    for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
      if (theInputVars[ivar] != inputVars[ivar]) {
	std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
		  << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
	fStatusIsClean = false;
      }
    }

    // initialize min and max vectors (for normalisation)
    fVmin[0] = -1;
    fVmax[0] = 0.99999988079071;
    fVmin[1] = -1;
    fVmax[1] = 1;
    fVmin[2] = -1;
    fVmax[2] = 1;
    fVmin[3] = -1;
    fVmax[3] = 1;

    // initialize input variable types
    fType[0] = 'F';
    fType[1] = 'F';
    fType[2] = 'F';
    fType[3] = 'F';

    // initialize constants
    Initialize();

    // initialize transformation
    InitTransform();
  }

  // destructor
  virtual ~ReadMLPGluinoType7() {
    Clear(); // method-specific
  }

  // the classifier response
  // "inputValues" is a vector of input values in the same order as the 
  // variables given to the constructor
  double GetMvaValue( const std::vector<double>& inputValues ) const;

private:

  // method-specific destructor
  void Clear();

  // input variable transformation

  double fMin_1[3][4];
  double fMax_1[3][4];
  void InitTransform_1();
  void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
  void InitTransform();
  void Transform( std::vector<double> & iv, int sigOrBgd ) const;

  // common member variables
  const char* fClassName;

  const size_t fNvars;
  size_t GetNvar()           const { return fNvars; }
  char   GetType( int ivar ) const { return fType[ivar]; }

  // normalisation of input variables
  const bool fIsNormalised;
  bool IsNormalised() const { return fIsNormalised; }
  double fVmin[4];
  double fVmax[4];
  double NormVariable( double x, double xmin, double xmax ) const {
    // normalise to output range: [-1, 1]
    return 2*(x - xmin)/(xmax - xmin) - 1.0;
  }

  // type of input variable: 'F' or 'I'
  char   fType[4];

  // initialize internal variables
  void Initialize();
  double GetMvaValue__( const std::vector<double>& inputValues ) const;

  // private members (method specific)

  double ActivationFnc(double x) const;
  double OutputActivationFnc(double x) const;

  int fLayers;
  int fLayerSize[3];
  double fWeightMatrix0to1[11][5];   // weight matrix from layer 0 to 1
  double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

  double * fWeights[3];
};

inline void ReadMLPGluinoType7::Initialize()
{
  // build network structure
  fLayers = 3;
  fLayerSize[0] = 5; fWeights[0] = new double[5]; 
  fLayerSize[1] = 11; fWeights[1] = new double[11]; 
  fLayerSize[2] = 1; fWeights[2] = new double[1]; 
  // weight matrix from layer 0 to 1
  fWeightMatrix0to1[0][0] = -0.869712017598399;
  fWeightMatrix0to1[1][0] = 1.6241071112227;
  fWeightMatrix0to1[2][0] = 2.43608505547521;
  fWeightMatrix0to1[3][0] = 0.0328060189183841;
  fWeightMatrix0to1[4][0] = -4.84131187150445;
  fWeightMatrix0to1[5][0] = -1.73550405586686;
  fWeightMatrix0to1[6][0] = 0.624300559013045;
  fWeightMatrix0to1[7][0] = -0.664203025143242;
  fWeightMatrix0to1[8][0] = 1.42815196292694;
  fWeightMatrix0to1[9][0] = 0.745492916348342;
  fWeightMatrix0to1[0][1] = -1.77101877136269;
  fWeightMatrix0to1[1][1] = -0.0855513925935638;
  fWeightMatrix0to1[2][1] = -1.38997468650235;
  fWeightMatrix0to1[3][1] = -14.2719495124715;
  fWeightMatrix0to1[4][1] = -3.91378573393675;
  fWeightMatrix0to1[5][1] = 1.07526739921156;
  fWeightMatrix0to1[6][1] = -0.522415836619943;
  fWeightMatrix0to1[7][1] = 1.20668915439103;
  fWeightMatrix0to1[8][1] = 0.444111151576692;
  fWeightMatrix0to1[9][1] = 14.7042619674277;
  fWeightMatrix0to1[0][2] = -0.192011677627139;
  fWeightMatrix0to1[1][2] = 0.0876325394031402;
  fWeightMatrix0to1[2][2] = 1.60529779560098;
  fWeightMatrix0to1[3][2] = -0.811492248597174;
  fWeightMatrix0to1[4][2] = -0.888597632017384;
  fWeightMatrix0to1[5][2] = 1.35149411541893;
  fWeightMatrix0to1[6][2] = 0.15515449270345;
  fWeightMatrix0to1[7][2] = -3.26590870939896;
  fWeightMatrix0to1[8][2] = -2.37663610422712;
  fWeightMatrix0to1[9][2] = -0.314669494906827;
  fWeightMatrix0to1[0][3] = -0.709546801235978;
  fWeightMatrix0to1[1][3] = -0.327850297330112;
  fWeightMatrix0to1[2][3] = -0.546616167944032;
  fWeightMatrix0to1[3][3] = 8.57098296492027;
  fWeightMatrix0to1[4][3] = 0.740148970361354;
  fWeightMatrix0to1[5][3] = 0.136141355610268;
  fWeightMatrix0to1[6][3] = -3.09201828386879;
  fWeightMatrix0to1[7][3] = 1.85004873382543;
  fWeightMatrix0to1[8][3] = -0.219430422272192;
  fWeightMatrix0to1[9][3] = -0.730150370125124;
  fWeightMatrix0to1[0][4] = 2.69219799180394;
  fWeightMatrix0to1[1][4] = 2.53025195674389;
  fWeightMatrix0to1[2][4] = 1.13296448593939;
  fWeightMatrix0to1[3][4] = -3.23349550122542;
  fWeightMatrix0to1[4][4] = -7.66257419195722;
  fWeightMatrix0to1[5][4] = -4.08510317583491;
  fWeightMatrix0to1[6][4] = 0.901473127502826;
  fWeightMatrix0to1[7][4] = -0.813298002697466;
  fWeightMatrix0to1[8][4] = 1.60487040187545;
  fWeightMatrix0to1[9][4] = 16.2934379229673;
  // weight matrix from layer 1 to 2
  fWeightMatrix1to2[0][0] = -0.427721835144673;
  fWeightMatrix1to2[0][1] = -1.54910496612371;
  fWeightMatrix1to2[0][2] = -2.18859483488554;
  fWeightMatrix1to2[0][3] = 3.03600021175372;
  fWeightMatrix1to2[0][4] = -2.56051549468365;
  fWeightMatrix1to2[0][5] = -1.9554258588814;
  fWeightMatrix1to2[0][6] = -3.65003829005759;
  fWeightMatrix1to2[0][7] = -1.35130606193155;
  fWeightMatrix1to2[0][8] = -1.24148854644825;
  fWeightMatrix1to2[0][9] = 10.2193471369805;
  fWeightMatrix1to2[0][10] = -2.6114592657468;
}

inline double ReadMLPGluinoType7::GetMvaValue__( const std::vector<double>& inputValues ) const
{
  if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
    std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
    return 0;
  }

  for (int l=0; l<fLayers; l++)
    for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

  for (int l=0; l<fLayers-1; l++)
    fWeights[l][fLayerSize[l]-1]=1;

  for (int i=0; i<fLayerSize[0]-1; i++)
    fWeights[0][i]=inputValues[i];

  // layer 0 to 1
  for (int o=0; o<fLayerSize[1]-1; o++) {
    for (int i=0; i<fLayerSize[0]; i++) {
      double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
      fWeights[1][o] += inputVal;
    }
    fWeights[1][o] = ActivationFnc(fWeights[1][o]);
  }
  // layer 1 to 2
  for (int o=0; o<fLayerSize[2]; o++) {
    for (int i=0; i<fLayerSize[1]; i++) {
      double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
      fWeights[2][o] += inputVal;
    }
    fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
  }

  return fWeights[2][0];
}

double ReadMLPGluinoType7::ActivationFnc(double x) const {
  // sigmoid
  return 1.0/(1.0+exp(-x));
}
double ReadMLPGluinoType7::OutputActivationFnc(double x) const {
  // identity
  return x;
}
   
// Clean up
inline void ReadMLPGluinoType7::Clear() 
{
  // clean up the arrays
  for (int lIdx = 0; lIdx < 3; lIdx++) {
    delete[] fWeights[lIdx];
  }
}
inline double ReadMLPGluinoType7::GetMvaValue( const std::vector<double>& inputValues ) const
{
  // classifier response value
  double retval = 0;

  // classifier response, sanity check first
  if (!IsStatusClean()) {
    std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
	      << " because status is dirty" << std::endl;
    retval = 0;
  }
  else {
    if (IsNormalised()) {
      // normalise variables
      std::vector<double> iV;
      iV.reserve(inputValues.size());
      int ivar = 0;
      for (std::vector<double>::const_iterator varIt = inputValues.begin();
	   varIt != inputValues.end(); varIt++, ivar++) {
	iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
      }
      Transform( iV, -1 );
      retval = GetMvaValue__( iV );
    }
    else {
      std::vector<double> iV;
      int ivar = 0;
      for (std::vector<double>::const_iterator varIt = inputValues.begin();
	   varIt != inputValues.end(); varIt++, ivar++) {
	iV.push_back(*varIt);
      }
      Transform( iV, -1 );
      retval = GetMvaValue__( iV );
    }
  }

  return retval;
}

//_______________________________________________________________________
inline void ReadMLPGluinoType7::InitTransform_1()
{
  // Normalization transformation, initialisation
  fMin_1[0][0] = 112.112915039;
  fMax_1[0][0] = 3768.42919922;
  fMin_1[1][0] = 60.0310516357;
  fMax_1[1][0] = 1140.76147461;
  fMin_1[2][0] = 60.0310516357;
  fMax_1[2][0] = 3768.42919922;
  fMin_1[0][1] = 1.78046154976;
  fMax_1[0][1] = 31.8078384399;
  fMin_1[1][1] = 0.830619454384;
  fMax_1[1][1] = 492.651397705;
  fMin_1[2][1] = 0.830619454384;
  fMax_1[2][1] = 492.651397705;
  fMin_1[0][2] = -2.09703397751;
  fMax_1[0][2] = 2.09895896912;
  fMin_1[1][2] = -2.09951782227;
  fMax_1[1][2] = 2.09895849228;
  fMin_1[2][2] = -2.09951782227;
  fMax_1[2][2] = 2.09895896912;
  fMin_1[0][3] = 1.02580487728;
  fMax_1[0][3] = 6.11021947861;
  fMin_1[1][3] = 1.05000030994;
  fMax_1[1][3] = 4607.02197266;
  fMin_1[2][3] = 1.02580487728;
  fMax_1[2][3] = 4607.02197266;
}

//_______________________________________________________________________
inline void ReadMLPGluinoType7::Transform_1( std::vector<double>& iv, int cls) const
{
  // Normalization transformation
  if (cls < 0 || cls > 2) {
    if (2 > 1 ) cls = 2;
    else cls = 2;
  }
  const int nVar = 4;

  // get indices of used variables

  // define the indices of the variables which are transformed by this transformation
  static std::vector<int> indicesGet;
  static std::vector<int> indicesPut;

  if ( indicesGet.empty() ) { 
    indicesGet.reserve(fNvars);
    indicesGet.push_back( 0);
    indicesGet.push_back( 1);
    indicesGet.push_back( 2);
    indicesGet.push_back( 3);
  } 
  if ( indicesPut.empty() ) { 
    indicesPut.reserve(fNvars);
    indicesPut.push_back( 0);
    indicesPut.push_back( 1);
    indicesPut.push_back( 2);
    indicesPut.push_back( 3);
  } 

  static std::vector<double> dv;
  dv.resize(nVar);
  for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
  for (int ivar=0;ivar<4;ivar++) {
    double offset = fMin_1[cls][ivar];
    double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
    iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
  }
}

//_______________________________________________________________________
inline void ReadMLPGluinoType7::InitTransform()
{
  InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPGluinoType7::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
  Transform_1( iv, sigOrBgd );
}
