// Class: ReadMLPPPStauType7
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================
#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-
Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/05       [393733]
Creator        : aackert
Date           : Tue Feb 14 16:44:41 2017
Host           : Linux cmsbuild12.cern.ch 2.6.32-573.7.1.el6.x86_64 #1 SMP Wed Sep 23 10:12:03 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/aackert/private/CMSSW_7_4_15/src/MVA/exercises/03_TMVA
Training events: 20000
Analysis type  : [Classification]
#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-
# Set by User:
HiddenLayers: "10" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
# Default:
NCycles: "500" [Number of training cycles]
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##
#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-
NVar 4
P                             P                             P                             P                                                               'F'    [60.0310516357,2777.18359375]
Ih                            Ih                            Ih                            Ih                                                              'F'    [0.830619454384,492.651397705]
eta                           eta                           eta                           eta                                                             'F'    [-2.09951782227,2.09895849228]
TOF                           TOF                           TOF                           TOF                                                             'F'    [1.02504336834,4607.02197266]
NSpec 0
============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

public:

  // constructor
  IClassifierReader() : fStatusIsClean( true ) {}
  virtual ~IClassifierReader() {}

  // return classifier response
  virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

  // returns classifier status
  bool IsStatusClean() const { return fStatusIsClean; }

protected:

  bool fStatusIsClean;
};

#endif

class ReadMLPPPStauType7 : public IClassifierReader {

public:

  // constructor
  ReadMLPPPStauType7( std::vector<std::string>& theInputVars ) 
    : IClassifierReader(),
      fClassName( "ReadMLPPPStauType7" ),
      fNvars( 4 ),
      fIsNormalised( false )
  {      
    // the training input variables
    const char* inputVars[] = { "P", "Ih", "eta", "TOF" };

    // sanity checks
    if (theInputVars.size() <= 0) {
      std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
      fStatusIsClean = false;
    }

    if (theInputVars.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
		<< theInputVars.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
    }

    // validate input variables
    for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
      if (theInputVars[ivar] != inputVars[ivar]) {
	std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
		  << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
	fStatusIsClean = false;
      }
    }

    // initialize min and max vectors (for normalisation)
    fVmin[0] = -1;
    fVmax[0] = 1;
    fVmin[1] = -1;
    fVmax[1] = 1;
    fVmin[2] = -1;
    fVmax[2] = 1;
    fVmin[3] = -1;
    fVmax[3] = 1;

    // initialize input variable types
    fType[0] = 'F';
    fType[1] = 'F';
    fType[2] = 'F';
    fType[3] = 'F';

    // initialize constants
    Initialize();

    // initialize transformation
    InitTransform();
  }

  // destructor
  virtual ~ReadMLPPPStauType7() {
    Clear(); // method-specific
  }

  // the classifier response
  // "inputValues" is a vector of input values in the same order as the 
  // variables given to the constructor
  double GetMvaValue( const std::vector<double>& inputValues ) const;

private:

  // method-specific destructor
  void Clear();

  // input variable transformation

  double fMin_1[3][4];
  double fMax_1[3][4];
  void InitTransform_1();
  void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
  void InitTransform();
  void Transform( std::vector<double> & iv, int sigOrBgd ) const;

  // common member variables
  const char* fClassName;

  const size_t fNvars;
  size_t GetNvar()           const { return fNvars; }
  char   GetType( int ivar ) const { return fType[ivar]; }

  // normalisation of input variables
  const bool fIsNormalised;
  bool IsNormalised() const { return fIsNormalised; }
  double fVmin[4];
  double fVmax[4];
  double NormVariable( double x, double xmin, double xmax ) const {
    // normalise to output range: [-1, 1]
    return 2*(x - xmin)/(xmax - xmin) - 1.0;
  }

  // type of input variable: 'F' or 'I'
  char   fType[4];

  // initialize internal variables
  void Initialize();
  double GetMvaValue__( const std::vector<double>& inputValues ) const;

  // private members (method specific)

  double ActivationFnc(double x) const;
  double OutputActivationFnc(double x) const;

  int fLayers;
  int fLayerSize[3];
  double fWeightMatrix0to1[11][5];   // weight matrix from layer 0 to 1
  double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

  double * fWeights[3];
};

inline void ReadMLPPPStauType7::Initialize()
{
  // build network structure
  fLayers = 3;
  fLayerSize[0] = 5; fWeights[0] = new double[5]; 
  fLayerSize[1] = 11; fWeights[1] = new double[11]; 
  fLayerSize[2] = 1; fWeights[2] = new double[1]; 
  // weight matrix from layer 0 to 1
  fWeightMatrix0to1[0][0] = 2.77539667688714;
  fWeightMatrix0to1[1][0] = 0.644570938054767;
  fWeightMatrix0to1[2][0] = 0.659477320567225;
  fWeightMatrix0to1[3][0] = 16.4314013607934;
  fWeightMatrix0to1[4][0] = -1.20377134814342;
  fWeightMatrix0to1[5][0] = -6.18467761555733;
  fWeightMatrix0to1[6][0] = -0.671381101773207;
  fWeightMatrix0to1[7][0] = 6.36380457166061;
  fWeightMatrix0to1[8][0] = -8.11819541572124;
  fWeightMatrix0to1[9][0] = 7.69677160205721;
  fWeightMatrix0to1[0][1] = -12.4443389377194;
  fWeightMatrix0to1[1][1] = -0.715270416408138;
  fWeightMatrix0to1[2][1] = -4.6424414205091;
  fWeightMatrix0to1[3][1] = -2.10728783185092;
  fWeightMatrix0to1[4][1] = -1.22105767312283;
  fWeightMatrix0to1[5][1] = 5.71151678107681;
  fWeightMatrix0to1[6][1] = -0.611257913085872;
  fWeightMatrix0to1[7][1] = -8.41824422181722;
  fWeightMatrix0to1[8][1] = 21.2743338210802;
  fWeightMatrix0to1[9][1] = 7.78642826428738;
  fWeightMatrix0to1[0][2] = 1.35189956034213;
  fWeightMatrix0to1[1][2] = 0.683128188614033;
  fWeightMatrix0to1[2][2] = 2.57685715054198;
  fWeightMatrix0to1[3][2] = -15.3583151535005;
  fWeightMatrix0to1[4][2] = -2.37203125693916;
  fWeightMatrix0to1[5][2] = -7.17927184817247;
  fWeightMatrix0to1[6][2] = 0.386531452988292;
  fWeightMatrix0to1[7][2] = 1.46254162476345;
  fWeightMatrix0to1[8][2] = 0.0855160763364011;
  fWeightMatrix0to1[9][2] = -0.209899436605802;
  fWeightMatrix0to1[0][3] = 4.65881777160137;
  fWeightMatrix0to1[1][3] = -1.64757747953835;
  fWeightMatrix0to1[2][3] = -1.50778040719604;
  fWeightMatrix0to1[3][3] = -7.15042983581245;
  fWeightMatrix0to1[4][3] = 0.821896118207673;
  fWeightMatrix0to1[5][3] = 0.331370235329345;
  fWeightMatrix0to1[6][3] = -2.54749211643666;
  fWeightMatrix0to1[7][3] = -2.66887986940438;
  fWeightMatrix0to1[8][3] = -3.91969296162209;
  fWeightMatrix0to1[9][3] = 1.16802570128309;
  fWeightMatrix0to1[0][4] = -2.11538448391153;
  fWeightMatrix0to1[1][4] = 3.79004561684768;
  fWeightMatrix0to1[2][4] = 2.64309113612599;
  fWeightMatrix0to1[3][4] = 16.5167168984897;
  fWeightMatrix0to1[4][4] = -5.42560648050343;
  fWeightMatrix0to1[5][4] = -11.0852850511799;
  fWeightMatrix0to1[6][4] = 1.29683059002488;
  fWeightMatrix0to1[7][4] = -3.51954097138045;
  fWeightMatrix0to1[8][4] = 11.3947485861733;
  fWeightMatrix0to1[9][4] = 14.5776758102338;
  // weight matrix from layer 1 to 2
  fWeightMatrix1to2[0][0] = 10.7206331022362;
  fWeightMatrix1to2[0][1] = -4.05014759656473;
  fWeightMatrix1to2[0][2] = -2.95104546869849;
  fWeightMatrix1to2[0][3] = 0.256349202866192;
  fWeightMatrix1to2[0][4] = -1.72926333953532;
  fWeightMatrix1to2[0][5] = -3.23592916141975;
  fWeightMatrix1to2[0][6] = -4.159853343555;
  fWeightMatrix1to2[0][7] = -2.51011394736638;
  fWeightMatrix1to2[0][8] = 7.73100226835328;
  fWeightMatrix1to2[0][9] = 9.30270804448763;
  fWeightMatrix1to2[0][10] = -5.49894417546259;
}

inline double ReadMLPPPStauType7::GetMvaValue__( const std::vector<double>& inputValues ) const
{
  if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
    std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
    return 0;
  }

  for (int l=0; l<fLayers; l++)
    for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

  for (int l=0; l<fLayers-1; l++)
    fWeights[l][fLayerSize[l]-1]=1;

  for (int i=0; i<fLayerSize[0]-1; i++)
    fWeights[0][i]=inputValues[i];

  // layer 0 to 1
  for (int o=0; o<fLayerSize[1]-1; o++) {
    for (int i=0; i<fLayerSize[0]; i++) {
      double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
      fWeights[1][o] += inputVal;
    }
    fWeights[1][o] = ActivationFnc(fWeights[1][o]);
  }
  // layer 1 to 2
  for (int o=0; o<fLayerSize[2]; o++) {
    for (int i=0; i<fLayerSize[1]; i++) {
      double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
      fWeights[2][o] += inputVal;
    }
    fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
  }

  return fWeights[2][0];
}

double ReadMLPPPStauType7::ActivationFnc(double x) const {
  // sigmoid
  return 1.0/(1.0+exp(-x));
}
double ReadMLPPPStauType7::OutputActivationFnc(double x) const {
  // identity
  return x;
}
   
// Clean up
inline void ReadMLPPPStauType7::Clear() 
{
  // clean up the arrays
  for (int lIdx = 0; lIdx < 3; lIdx++) {
    delete[] fWeights[lIdx];
  }
}
inline double ReadMLPPPStauType7::GetMvaValue( const std::vector<double>& inputValues ) const
{
  // classifier response value
  double retval = 0;

  // classifier response, sanity check first
  if (!IsStatusClean()) {
    std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
	      << " because status is dirty" << std::endl;
    retval = 0;
  }
  else {
    if (IsNormalised()) {
      // normalise variables
      std::vector<double> iV;
      iV.reserve(inputValues.size());
      int ivar = 0;
      for (std::vector<double>::const_iterator varIt = inputValues.begin();
	   varIt != inputValues.end(); varIt++, ivar++) {
	iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
      }
      Transform( iV, -1 );
      retval = GetMvaValue__( iV );
    }
    else {
      std::vector<double> iV;
      int ivar = 0;
      for (std::vector<double>::const_iterator varIt = inputValues.begin();
	   varIt != inputValues.end(); varIt++, ivar++) {
	iV.push_back(*varIt);
      }
      Transform( iV, -1 );
      retval = GetMvaValue__( iV );
    }
  }

  return retval;
}

//_______________________________________________________________________
inline void ReadMLPPPStauType7::InitTransform_1()
{
  // Normalization transformation, initialisation
  fMin_1[0][0] = 113.703414917;
  fMax_1[0][0] = 2777.18359375;
  fMin_1[1][0] = 60.0310516357;
  fMax_1[1][0] = 1140.76147461;
  fMin_1[2][0] = 60.0310516357;
  fMax_1[2][0] = 2777.18359375;
  fMin_1[0][1] = 1.96218657494;
  fMax_1[0][1] = 17.5997142792;
  fMin_1[1][1] = 0.830619454384;
  fMax_1[1][1] = 492.651397705;
  fMin_1[2][1] = 0.830619454384;
  fMax_1[2][1] = 492.651397705;
  fMin_1[0][2] = -2.09754776955;
  fMax_1[0][2] = 2.09893035889;
  fMin_1[1][2] = -2.09951782227;
  fMax_1[1][2] = 2.09895849228;
  fMin_1[2][2] = -2.09951782227;
  fMax_1[2][2] = 2.09895849228;
  fMin_1[0][3] = 1.02504336834;
  fMax_1[0][3] = 3.63803482056;
  fMin_1[1][3] = 1.05000030994;
  fMax_1[1][3] = 4607.02197266;
  fMin_1[2][3] = 1.02504336834;
  fMax_1[2][3] = 4607.02197266;
}

//_______________________________________________________________________
inline void ReadMLPPPStauType7::Transform_1( std::vector<double>& iv, int cls) const
{
  // Normalization transformation
  if (cls < 0 || cls > 2) {
    if (2 > 1 ) cls = 2;
    else cls = 2;
  }
  const int nVar = 4;

  // get indices of used variables

  // define the indices of the variables which are transformed by this transformation
  static std::vector<int> indicesGet;
  static std::vector<int> indicesPut;

  if ( indicesGet.empty() ) { 
    indicesGet.reserve(fNvars);
    indicesGet.push_back( 0);
    indicesGet.push_back( 1);
    indicesGet.push_back( 2);
    indicesGet.push_back( 3);
  } 
  if ( indicesPut.empty() ) { 
    indicesPut.reserve(fNvars);
    indicesPut.push_back( 0);
    indicesPut.push_back( 1);
    indicesPut.push_back( 2);
    indicesPut.push_back( 3);
  } 

  static std::vector<double> dv;
  dv.resize(nVar);
  for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
  for (int ivar=0;ivar<4;ivar++) {
    double offset = fMin_1[cls][ivar];
    double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
    iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
  }
}

//_______________________________________________________________________
inline void ReadMLPPPStauType7::InitTransform()
{
  InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPPPStauType7::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
  Transform_1( iv, sigOrBgd );
}
