export PATH=$HOME/external/fbm.2004-11-10/bin:$PATH
export PATH=`pwd`/bin:$PATH
export LD_LIBRARY_PATH=$ROOTSYS/lib:$PYTHONDIR/lib:$LD_LIBRARY_PATH
export PYTHONPATH=`pwd`/python:$PYTHONPATH
#export PYTHONPATH=$ROOTSYS/lib:$PYTHONPATH
#export LD_LIBRARY_PATH=`pwd`/01_RGS:$LD_LIBRARY_PATH

