// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/05       [393733]
Creator        : aackert
Date           : Sun Mar 12 19:22:26 2017
Host           : Linux cmsbuild12.cern.ch 2.6.32-573.7.1.el6.x86_64 #1 SMP Wed Sep 23 10:12:03 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/aackert/private/CMSSW_7_4_15/src/MVA/exercises/03_TMVA
Training events: 20000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "15" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
# Default:
NCycles: "500" [Number of training cycles]
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
P                             P                             P                             P                                                               'F'    [60.0310516357,1823.05090332]
Ih                            Ih                            Ih                            Ih                                                              'F'    [0.830619454384,492.651397705]
eta                           eta                           eta                           eta                                                             'F'    [-2.09951782227,2.09983992577]
TOF                           TOF                           TOF                           TOF                                                             'F'    [1.02542364597,4607.02197266]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "P", "Ih", "eta", "TOF" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][4];
   double fMax_1[3][4];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][5];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 5; fWeights[0] = new double[5]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.24722981810874;
   fWeightMatrix0to1[1][0] = 2.81580740911439;
   fWeightMatrix0to1[2][0] = -0.770466687846474;
   fWeightMatrix0to1[3][0] = 2.14343082345247;
   fWeightMatrix0to1[4][0] = -2.84242987748636;
   fWeightMatrix0to1[5][0] = -1.77227504099589;
   fWeightMatrix0to1[6][0] = 0.872306536657173;
   fWeightMatrix0to1[7][0] = 7.17208840093656;
   fWeightMatrix0to1[8][0] = -6.7686329759421;
   fWeightMatrix0to1[9][0] = -0.4921002455099;
   fWeightMatrix0to1[10][0] = -5.0990372127247;
   fWeightMatrix0to1[11][0] = -0.18404196489444;
   fWeightMatrix0to1[12][0] = -1.50861202972007;
   fWeightMatrix0to1[13][0] = -1.86240218896699;
   fWeightMatrix0to1[14][0] = -2.12099277909485;
   fWeightMatrix0to1[0][1] = 4.40772056439672;
   fWeightMatrix0to1[1][1] = 3.0387089436764;
   fWeightMatrix0to1[2][1] = 16.109176112577;
   fWeightMatrix0to1[3][1] = 0.524860714498043;
   fWeightMatrix0to1[4][1] = 3.84480224108081;
   fWeightMatrix0to1[5][1] = 0.48254362540803;
   fWeightMatrix0to1[6][1] = -1.81724177046347;
   fWeightMatrix0to1[7][1] = 6.32683148055201;
   fWeightMatrix0to1[8][1] = 5.39896173437302;
   fWeightMatrix0to1[9][1] = -2.72869863210901;
   fWeightMatrix0to1[10][1] = -3.26450909199347;
   fWeightMatrix0to1[11][1] = 5.89581443002697;
   fWeightMatrix0to1[12][1] = -1.69787074085768;
   fWeightMatrix0to1[13][1] = -20.4522008494543;
   fWeightMatrix0to1[14][1] = 3.30382722216249;
   fWeightMatrix0to1[0][2] = 2.73296302363888;
   fWeightMatrix0to1[1][2] = 0.297725995804239;
   fWeightMatrix0to1[2][2] = -0.126385761867571;
   fWeightMatrix0to1[3][2] = 0.527064331183342;
   fWeightMatrix0to1[4][2] = -0.532785188658195;
   fWeightMatrix0to1[5][2] = 0.402597107403848;
   fWeightMatrix0to1[6][2] = -1.64600022415448;
   fWeightMatrix0to1[7][2] = 1.13957794740169;
   fWeightMatrix0to1[8][2] = 3.28574497145757;
   fWeightMatrix0to1[9][2] = 1.85458414472918;
   fWeightMatrix0to1[10][2] = 2.97365890435211;
   fWeightMatrix0to1[11][2] = -4.36944358588743;
   fWeightMatrix0to1[12][2] = 1.35371613522353;
   fWeightMatrix0to1[13][2] = 0.0181975307958393;
   fWeightMatrix0to1[14][2] = 0.617952926210717;
   fWeightMatrix0to1[0][3] = -5.34267032301268;
   fWeightMatrix0to1[1][3] = -0.900116353876825;
   fWeightMatrix0to1[2][3] = -9.56988031619389;
   fWeightMatrix0to1[3][3] = 1.07875638156691;
   fWeightMatrix0to1[4][3] = 2.38371032566028;
   fWeightMatrix0to1[5][3] = -1.43147391398083;
   fWeightMatrix0to1[6][3] = -0.980259565909825;
   fWeightMatrix0to1[7][3] = -4.73510279958674;
   fWeightMatrix0to1[8][3] = 0.811125550071972;
   fWeightMatrix0to1[9][3] = -0.21475793195505;
   fWeightMatrix0to1[10][3] = 4.80880716670885;
   fWeightMatrix0to1[11][3] = -4.21601972040004;
   fWeightMatrix0to1[12][3] = -1.741180462266;
   fWeightMatrix0to1[13][3] = 8.77594152474424;
   fWeightMatrix0to1[14][3] = -3.72427550364485;
   fWeightMatrix0to1[0][4] = -2.63089635743042;
   fWeightMatrix0to1[1][4] = -1.60424696049499;
   fWeightMatrix0to1[2][4] = 4.87207742068184;
   fWeightMatrix0to1[3][4] = 2.91919176258709;
   fWeightMatrix0to1[4][4] = 4.40725215214282;
   fWeightMatrix0to1[5][4] = 1.78825867051301;
   fWeightMatrix0to1[6][4] = 2.23432441010083;
   fWeightMatrix0to1[7][4] = 3.70355282367094;
   fWeightMatrix0to1[8][4] = -2.0526824939441;
   fWeightMatrix0to1[9][4] = -0.169085123220069;
   fWeightMatrix0to1[10][4] = -1.59050415775322;
   fWeightMatrix0to1[11][4] = 2.12135425629522;
   fWeightMatrix0to1[12][4] = 1.41462085286835;
   fWeightMatrix0to1[13][4] = -12.6260860887169;
   fWeightMatrix0to1[14][4] = -1.00020852413649;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -3.66991753467411;
   fWeightMatrix1to2[0][1] = 1.91504485297721;
   fWeightMatrix1to2[0][2] = -10.4006811228621;
   fWeightMatrix1to2[0][3] = -0.96657662087987;
   fWeightMatrix1to2[0][4] = 4.01859531521074;
   fWeightMatrix1to2[0][5] = 2.03913320750387;
   fWeightMatrix1to2[0][6] = 2.70307408917297;
   fWeightMatrix1to2[0][7] = 0.410120578934733;
   fWeightMatrix1to2[0][8] = 1.34537596494491;
   fWeightMatrix1to2[0][9] = -0.746777635619879;
   fWeightMatrix1to2[0][10] = 1.34058747750578;
   fWeightMatrix1to2[0][11] = -1.2337421889292;
   fWeightMatrix1to2[0][12] = 0.7687530337904;
   fWeightMatrix1to2[0][13] = -10.7495084353074;
   fWeightMatrix1to2[0][14] = 4.53739768946096;
   fWeightMatrix1to2[0][15] = 0.217617631491157;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 121.724395752;
   fMax_1[0][0] = 1823.05090332;
   fMin_1[1][0] = 60.0310516357;
   fMax_1[1][0] = 1140.76147461;
   fMin_1[2][0] = 60.0310516357;
   fMax_1[2][0] = 1823.05090332;
   fMin_1[0][1] = 2.78451633453;
   fMax_1[0][1] = 28.4964256287;
   fMin_1[1][1] = 0.830619454384;
   fMax_1[1][1] = 492.651397705;
   fMin_1[2][1] = 0.830619454384;
   fMax_1[2][1] = 492.651397705;
   fMin_1[0][2] = -2.09927392006;
   fMax_1[0][2] = 2.09983992577;
   fMin_1[1][2] = -2.09951782227;
   fMax_1[1][2] = 2.09895849228;
   fMin_1[2][2] = -2.09951782227;
   fMax_1[2][2] = 2.09983992577;
   fMin_1[0][3] = 1.02542364597;
   fMax_1[0][3] = 3.70292830467;
   fMin_1[1][3] = 1.05000030994;
   fMax_1[1][3] = 4607.02197266;
   fMin_1[2][3] = 1.02542364597;
   fMax_1[2][3] = 4607.02197266;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 4;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<4;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
